Update test-cicd.yml

diff --git a/.github/workflows/test-cicd.yml b/.github/workflows/test-cicd.yml
--- a/.github/workflows/test-cicd.yml
+++ b/.github/workflows/test-cicd.yml
@@ -57,7 +57,7 @@ jobs:
         docker compose -f docker-compose-test.yml push
 
     # 8. SSH로 EC2 연결 및 배포
-    - name: Deploy to EC2
+    - name: Deploy to EC2 Instance 1
       uses: appleboy/ssh-action@v1.2.0
       with:
         key: ${{secrets.EC2_KEY}}
@@ -68,3 +68,28 @@ jobs:
           sudo docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}
           sudo docker compose pull
           sudo docker compose -f ./docker-compose-test.yml up -d
+          sleep 1m
+          if curl -f http://localhost:8000/actuator/health; then
+            echo "Instance 1 is healthy."
+          else
+            echo "Instance 1 health check failed."
+            exit 1
+          fi
+    - name: Deploy to EC2 Instance 2
+      uses: appleboy/ssh-action@v1.2.0
+      with:
+        key: ${{ secrets.EC2_KEY }}
+        host: ${{ secrets.EC2_HOST_2 }}
+        username: ubuntu
+        script: |
+          whoami
+          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
+          sudo docker compose pull
+          sudo docker compose -f ./docker-compose-test.yml up -d
+          sleep 1m
+          if curl -f http://localhost:8000/actuator/health; then
+            echo "Instance 2 is healthy."
+          else
+            echo "Instance 2 health check failed."
+            exit 1
+          fi
